version: '3.8'

services:
    app:
        image: duralas/messages_rp/app_dev_php
        container_name: duralas_messages_rp_app_dev_php
        build:
            context: ./php
        volumes:
            - ../../:/var/www/html
        networks:
            - duralas_messages_rp_network

    nginx:
        image: nginx
        depends_on:
            - app
        volumes:
            - ../../:/var/www/html
            - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        networks:
            - duralas_messages_rp_network

networks:
    duralas_messages_rp_network:
